kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control plane nodes
  - role: control-plane

  # Worker nodes
  # In order for an Ingress to work in your cluster, there must be an ingress controller running. 
  # You need to select at least one ingress controller and make sure it is set up in your cluster.
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        apiVersion: kubeadm.k8s.io/v1beta4
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP